Patch 6.1.362 Problem:    tgetent() may return zero for success. tgetflag() may return -1 	    for an error. Solution:   Check tgetflag() for returning a positive value.  Add an autoconf 	    check for the value that tgetent() returns. Files:	    src/auto/configure, src/config.h.in, src/configure.in, src/term.c

diff --git a/src/auto/configure b/src/auto/configure
--- a/src/auto/configure
+++ b/src/auto/configure
@@ -5423,10 +5423,43 @@ else
   echo "$ac_t""none found" 1>&6
 fi
 
+if test "x$olibs" != "x$LIBS"; then
+  echo $ac_n "checking what tgetent() returns for an unknown terminal""... $ac_c" 1>&6
+echo "configure:5507: checking what tgetent() returns for an unknown terminal" >&5
+  if test "$cross_compiling" = yes; then
+  { echo "configure: error: failed to compile test program." 1>&2; exit 1; }
+else
+  cat > conftest.$ac_ext <<EOF
+#line 5512 "configure"
+#include "confdefs.h"
+
+#ifdef HAVE_TERMCAP_H
+# include <termcap.h>
+#endif
+main()
+{char s[10000]; int res = tgetent(s, "thisterminaldoesnotexist"); exit(res != 0); }
+EOF
+if { (eval echo configure:5521: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+then
+  echo "$ac_t""zero" 1>&6; cat >> confdefs.h <<\EOF
+#define TGETENT_ZERO_ERR 0
+EOF
+
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+  echo "$ac_t""non-zero" 1>&6
+fi
+rm -fr conftest*
+fi
+
+fi
+
 echo $ac_n "checking whether termcap.h contains ospeed""... $ac_c" 1>&6
-echo "configure:5381: checking whether termcap.h contains ospeed" >&5
+echo "configure:5539: checking whether termcap.h contains ospeed" >&5
 cat > conftest.$ac_ext <<EOF
-#line 5383 "configure"
+#line 5541 "configure"
 #include "confdefs.h"
 
 #ifdef HAVE_TERMCAP_H
